// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Notisight.Api.Infrastructure.Persistence;

#nullable disable

namespace Notisight.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260705120000_AddNoteDurationSeconds")]
    partial class AddNoteDurationSeconds
    {
    }
}
